### ISSUE TITLE
Add pages in the menu

### ISSUE THREAD

**Issue by easybeau** [Kexin-Li/hexo-theme-cicada#2]
Hi,

Thanks for this beautiful theme!

I would like to add pages to desplay in the menu.

I created a new page : `hexo new page team`
Then I put it in the nav menu 
team: /team

The result is that the menu is hidden.

Could you help me please.
Thanks
Isabelle

**Comment by Kexin-Li** [comment]
Hi Isabelle,

Thanks for using my theme :)

Do you mean hidden is `menu.team`?

<img width="386" alt="2018-10-04 20 41 09" src="https://user-images.githubusercontent.com/21211353/46474792-5ffc3500-c816-11e8-8606-217d6cb6b4e9.png">

If so, you should add Internationalization name in file `cicada/language`:

```
menu:
  team: team
```

**Comment by easybeau** [comment]
Hey, thanks for your answer!

I got this problem. Ok... it's a question of language. I will add team to the right language.

Cheers
